ZSH Added command_exists

diff --git a/zsh/dot-zshrc b/zsh/dot-zshrc
--- a/zsh/dot-zshrc
+++ b/zsh/dot-zshrc
@@ -1,5 +1,5 @@
 # /usr/bin/zsh
-# Zsh 5.9.1
+# Zsh 5.9.2
 
 # --- OPTIONS ---
 
@@ -12,24 +12,32 @@ bindkey ^H vi-backward-kill-word
 
 # --- ENVIRONMENT VARIABLES ---
 
+command_exists() {
+    command -v "$1" > /dev/null 2>&1
+}
+
 export PATH="$HOME/.local/bin:$PATH"
 
-if command -v "pnpm" > /dev/null 2>&1; then
-    export PATH="$PATH:$HOME/.local/share/pnpm/bin"
-fi
+command_exists "pnpm" && export PATH="$PATH:$HOME/.local/share/pnpm/bin"
+command_exists "nvim" && export EDITOR="nvim" || export EDITOR="vim"
 
-export EDITOR="vim"
-export STOW_DIR="$HOME/dotfiles"
+[[ -d "$HOME/dotfiles" ]] && export STOW_DIR="$HOME/dotfiles"
 
 # --- ALIASES ---
 
 alias ls="ls --color=auto"
-alias tree="tree -C"
-alias vim="nvim"
+
+command_exists "tree" && alias tree="tree -C"
+command_exists "nvim" && alias vim="nvim"
 
 # --- CUSTOM FUNCTIONS ---
 
 omptheme() {
+    if ! command_exists "oh-my-posh"; then
+        echo "Error: oh-my-posh is not installed." >&2
+        return 1
+    fi
+
     local ompconfig="$HOME/.config/oh-my-posh"
     omptheme="$ompconfig/$1.toml"
     if [[ ! -f "$omptheme" ]]; then
@@ -40,27 +48,28 @@ omptheme() {
     eval $(oh-my-posh init zsh -c "$omptheme")
 }
 
-dot-zsh () {
-    local p="$HOME/.zshrc"
-    . "$p"
-    echo "Reloaded $p"
+dot-zsh() {
+    . "$HOME/.zshrc"
 }
 
 # --- INIT ---
 
 if [[ $(tty) == /dev/tty* ]]; then
-    omptheme simple
+    command_exists "oh-my-posh" && omptheme simple
 
-    if command -v fastfetch > /dev/null 2>&1 then
+    if command_exists "fastfetch"; then
         fastfetch
-    elif command -v neofetch > /dev/null 2>&1 then
+    elif command_exists "neofetch"; then
         neofetch
     fi
 else
-    omptheme main
+    command_exists "oh-my-posh" && omptheme main
 fi
 
-# pyenv init
-export PYENV_ROOT="$HOME/.pyenv"
-[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
-eval "$(pyenv init - zsh)"
+if command_exists "pyenv"; then
+    export PYENV_ROOT="$HOME/.pyenv"
+    [[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
+    eval "$(pyenv init - zsh)"
+fi
+
+unset -f command_exists
